package com.srivenkateswarahostel.controller;

import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class RootController {

    @GetMapping(value = "/", produces = MediaType.TEXT_HTML_VALUE)
    @ResponseBody
    public String index() {
        return "<!DOCTYPE html>"
                + "<html lang=\"en\">"
                + "<head>"
                + "  <meta charset=\"UTF-8\" />"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />"
                + "  <title>Sri Venkateswara Boys Hostel - API Server</title>"
                + "  <style>"
                + "    * { box-sizing: border-box; margin: 0; padding: 0; }"
                + "    body {"
                + "      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;"
                + "      background-color: #0f172a;"
                + "      color: #f8fafc;"
                + "      display: flex;"
                + "      align-items: center;"
                + "      justify-content: center;"
                + "      min-height: 100vh;"
                + "      padding: 20px;"
                + "    }"
                + "    .card {"
                + "      background-color: #1e293b;"
                + "      border: 1px solid rgba(255, 255, 255, 0.1);"
                + "      border-radius: 16px;"
                + "      box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.4), 0 8px 10px -6px rgba(0, 0, 0, 0.2);"
                + "      max-width: 520px;"
                + "      width: 100%;"
                + "      padding: 40px;"
                + "      text-align: center;"
                + "    }"
                + "    .badge {"
                + "      display: inline-flex;"
                + "      align-items: center;"
                + "      gap: 6px;"
                + "      background-color: rgba(16, 185, 129, 0.15);"
                + "      color: #10b981;"
                + "      padding: 6px 14px;"
                + "      border-radius: 9999px;"
                + "      font-size: 13px;"
                + "      font-weight: 700;"
                + "      margin-bottom: 20px;"
                + "    }"
                + "    .badge-dot {"
                + "      width: 8px;"
                + "      height: 8px;"
                + "      background-color: #10b981;"
                + "      border-radius: 50%;"
                + "    }"
                + "    h1 {"
                + "      font-size: 24px;"
                + "      font-weight: 800;"
                + "      color: #ffffff;"
                + "      margin-bottom: 8px;"
                + "      letter-spacing: -0.5px;"
                + "    }"
                + "    .subtitle {"
                + "      font-size: 14px;"
                + "      color: #94a3b8;"
                + "      margin-bottom: 28px;"
                + "    }"
                + "    .info-box {"
                + "      background-color: rgba(15, 23, 42, 0.6);"
                + "      border: 1px solid rgba(255, 255, 255, 0.05);"
                + "      border-radius: 10px;"
                + "      padding: 16px;"
                + "      margin-bottom: 24px;"
                + "      font-size: 14px;"
                + "      color: #cbd5e1;"
                + "      line-height: 1.6;"
                + "    }"
                + "    .btn {"
                + "      display: block;"
                + "      width: 100%;"
                + "      background-color: #2563eb;"
                + "      color: #ffffff;"
                + "      padding: 14px 20px;"
                + "      border-radius: 10px;"
                + "      font-size: 15px;"
                + "      font-weight: 700;"
                + "      text-decoration: none;"
                + "      transition: background-color 0.2s ease;"
                + "      margin-bottom: 12px;"
                + "    }"
                + "    .btn:hover {"
                + "      background-color: #1d4ed8;"
                + "    }"
                + "    .link-swagger {"
                + "      color: #38bdf8;"
                + "      font-size: 13px;"
                + "      text-decoration: none;"
                + "      font-weight: 600;"
                + "    }"
                + "    .link-swagger:hover {"
                + "      text-decoration: underline;"
                + "    }"
                + "  </style>"
                + "</head>"
                + "<body>"
                + "  <div class=\"card\">"
                + "    <div class=\"badge\"><span class=\"badge-dot\"></span> API Service Online</div>"
                + "    <h1>Sri Venkateswara Boys Hostel</h1>"
                + "    <div class=\"subtitle\">Spring Boot Backend API Server (Port 8081)</div>"
                + "    <div class=\"info-box\">"
                + "      You have connected to the backend API service. To access the user interface and manage hostel operations, please launch the React frontend web application."
                + "    </div>"
                + "    <a class=\"btn\" href=\"http://localhost:5173\">Open Web Application Portal</a>"
                + "    <div><a class=\"link-swagger\" href=\"/swagger-ui/index.html\">Explore Swagger API Documentation &rarr;</a></div>"
                + "  </div>"
                + "</body>"
                + "</html>";
    }
}
